name: Go

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  tests:
    name: KCD Tests
    runs-on: ubuntu-latest
    steps:

      - name: set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          stable: true
        id: go

      - name: check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49.0

      - run: rm -rf examples

      - name: tests
        run: go test -v .

      - name: Calc coverage
        run: rm -rf examples ; ls ; go test -v -coverpkg=./...  -covermode=count -coverprofile=coverage.out ./...

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
